---
title: "Homework4"
author: "Boyan Wu"
format: html
---

```{r}
library(RedditExtractoR)
library(tidyverse)
library(tidytext)
```

```{r}
#| eval: false
write_rds(top_hk_urls, "top_hk_urls.rds")
write_rds(nba_user, "nba_user.rds")

```

```{r}
top_hk_urls <- read_rds("top_hk_urls.rds") 
nba_user <- read_rds("nba_user.rds")
```

```{r}
#| eval: false
# get data for a specific user
top_hk_urls <- find_thread_urls(subreddit="hollowknight", sort_by="top")
str(top_hk_urls)
hollowknight <- "data analysis"
```

```{r}
data(stop_words)
top_hk_urls_words <- top_hk_urls %>% 
  unnest_tokens(word, title) %>%
  anti_join(stop_words)

word_freq <- top_hk_urls_words %>% 
  count(word, sort = TRUE)

ggplot(head(word_freq, 10), aes(x = word, y = n)) +
  geom_col() +
  ggtitle("Top 10 Words in 'hollowknight' Subreddit Titles")

```


```{r}
#| eval: false
user <- "nba"
nba_user <- get_user_content(user)
str(nba_user)
str(nba_user[[user]]$about)
```

```{r}
#| eval: false
write_rds(pluckcomments, "pluckcomments.rds")
```

```{r}
#| eval: false
# extract the comments and convert to data frame
#mycomment <- nba_user[[user]]$comments

pluckcomments <- pluck(nba_user, user, "comments") %>%
  tibble()
#mycomments <- tibble(mycomments)
```


```{r}
pluckcomments <- read_rds("pluckcomments.rds")

nba_user_words <- pluckcomments %>% 
  unnest_tokens(word, thread_title) %>% 
  anti_join(stop_words)

word_freq <- nba_user_words %>% 
  count(word, sort = TRUE)

# show the top 10 words in a bar chart
ggplot(head(word_freq, 10), aes(x = word, y = n)) +
  geom_col() +
  ggtitle(paste("Top 10 Words in u/nba's Comments"))


```